// Autor: Javier Tomey. Gobierno de Aragón
// 
// Éste programa es software libre: usted tiene derecho a redistribuirlo y/o
// modificarlo bajo los términos de la Licencia EUPL European Public License 
// publicada por el organismo IDABC de la Comisión Europea, en su versión 1.2.
// o posteriores.
// 
// Éste programa se distribuye de buena fe, pero SIN NINGUNA GARANTÍA, incluso sin 
// las presuntas garantías implícitas de USABILIDAD o ADECUACIÓN A PROPÓSITO CONCRETO. 
// Para mas información consulte la Licencia EUPL European Public License.
// 
// Usted recibe una copia de la Licencia EUPL European Public License 
// junto con este programa, si por algún motivo no le es posible visualizarla, 
// puede consultarla en la siguiente URL: https://eupl.eu/1.2/es/
// 
// You should have received a copy of the EUPL European Public 
// License along with this program.  If not, see https://eupl.eu/1.2/en/
// 
// Vous devez avoir reçu une copie de la EUPL European Public
// License avec ce programme. Si non, voir https://eupl.eu/1.2/fr/
// 
// Sie sollten eine Kopie der EUPL European Public License zusammen mit
// diesem Programm. Wenn nicht, finden Sie da https://eupl.eu/1.2/de/

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLGOdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCION : CONTENIDO
    {
        public string RECURSOS_HUMANOS { get; set; }
        public string RECURSOS_HUMANOS_PDTE_VAL { get; set; }
        public string COSTE_ECONOMICO { get; set; }
        public string COSTE_ECONOMICO_PDTE_VAL { get; set; }
        public string INSTRUMENTOS_ACT { get; set; }
        public string INSTRUMENTOS_ACT_PDTE_VAL { get; set; }
        public string MEDIOS_OTROS { get; set; }
        public string MEDIOS_OTROS_PDTE_VAL { get; set; }
        public string TEMPORALIDAD { get; set; }
        public string TEMPORALIDAD_PDTE_VAL { get; set; }
        public string INDICADOR_SEGUIMIENTO { get; set; }
        public string INDICADOR_SEGUIMIENTO_PDTE_VAL { get; set; }
        public int OBJETIVO_CONTENIDO_ID { get; set; }
        public Nullable<int> ESTADO_SEGUIMIENTO_ID { get; set; }
        public Nullable<int> ESTADO_SEGUIMIENTO_ID_PDTE_VAL { get; set; }
        public string ORGANO_RESPONSABLE { get; set; }
        public string ORGANO_RESPONSABLE_PDTE_VAL { get; set; }
        public string SEGUIMIENTO { get; set; }
        public string SEGUIMIENTO_PDTE_VAL { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<byte> PORCENTAJE_AVANCE { get; set; }
        public Nullable<byte> PORCENTAJE_AVANCE_PDTE_VAL { get; set; }
    
        public virtual ESTADOS_SEGUIMIENTO ESTADOS_SEGUIMIENTO { get; set; }
        public virtual ESTADOS_SEGUIMIENTO ESTADOS_SEGUIMIENTO_PDTE_VAL { get; set; }
        public virtual OBJETIVO OBJETIVO { get; set; }
    }
}
