CREATE TABLE PLGO_OWN.APP_ARCHIVOS_GENERALES
(
  ID                     NUMBER(10)             NOT NULL,
  MANUAL_USUARIO         BLOB,
  NOMBRE_MANUAL_USUARIO  NVARCHAR2(75),
  MANUAL_ADMIN           BLOB,
  NOMBRE_MANUAL_ADMIN    NVARCHAR2(75)
)
LOB (MANUAL_USUARIO) STORE AS (
  TABLESPACE  PLGO_DAT
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
LOB (MANUAL_ADMIN) STORE AS (
  TABLESPACE  PLGO_DAT
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
TABLESPACE PLGO_DAT
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PLGO_OWN."AspNetRoles"
(
  "Id"    NVARCHAR2(128),
  "Name"  NVARCHAR2(256)
)
TABLESPACE PLGO_DAT
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PLGO_OWN."AspNetUsers"
(
  "Id"                    NVARCHAR2(128),
  "Email"                 NVARCHAR2(256),
  "EmailConfirmed"        NUMBER(1),
  "PasswordHash"          NVARCHAR2(256),
  "SecurityStamp"         NVARCHAR2(256),
  "PhoneNumber"           NVARCHAR2(256),
  "PhoneNumberConfirmed"  NUMBER(1),
  "TwoFactorEnabled"      NUMBER(1),
  "LockoutEndDateUtc"     TIMESTAMP(7),
  "LockoutEnabled"        NUMBER(1),
  "AccessFailedCount"     NUMBER(10),
  "UserName"              NVARCHAR2(256)
)
TABLESPACE PLGO_DAT
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PLGO_OWN.ESTADOS_SEGUIMIENTO
(
  ESTADO_SEGUIMIENTO_ID  NUMBER(10)             NOT NULL,
  DESCRIPCION            VARCHAR2(50 BYTE)      NOT NULL
)
TABLESPACE PLGO_DAT
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PLGO_OWN.ESTADOS_VALIDACION
(
  ESTADO_VALIDACION_ID  NUMBER(10)              NOT NULL,
  DESCRIPCION           VARCHAR2(50 BYTE)       NOT NULL
)
TABLESPACE PLGO_DAT
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PLGO_OWN.LEGISLATURA
(
  LEGISLATURA_ID  NUMBER(10)                    NOT NULL,
  DESCRIPCION     VARCHAR2(50 BYTE)             NOT NULL,
  ACTUAL          NUMBER(1)                     DEFAULT 0                     NOT NULL,
  FECHA_INICIO    DATE,
  FECHA_FIN       DATE
)
TABLESPACE PLGO_DAT
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PLGO_OWN.TIPO_CAMBIO_CONTENIDO
(
  TIPO_CAMBIO_ID  NUMBER(10)                    NOT NULL,
  TIPO_CAMBIO     VARCHAR2(100 BYTE)            NOT NULL
)
TABLESPACE PLGO_DAT
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PLGO_OWN."RoleNameIndex" ON PLGO_OWN."AspNetRoles"
("Name")
LOGGING
TABLESPACE PLGO_IDX
NOPARALLEL;


--  There is no statement for index PLGO_OWN.SYS_C008200.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX PLGO_OWN."UserNameIndex" ON PLGO_OWN."AspNetUsers"
("UserName")
LOGGING
TABLESPACE PLGO_IDX
NOPARALLEL;


--  There is no statement for index PLGO_OWN.SYS_C008201.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX PLGO_OWN.ESTADOS_OBJETIVOS_PK ON PLGO_OWN.ESTADOS_SEGUIMIENTO
(ESTADO_SEGUIMIENTO_ID)
LOGGING
TABLESPACE PLGO_IDX
NOPARALLEL;


CREATE UNIQUE INDEX PLGO_OWN.ESTADOS_VALIDACION_PK ON PLGO_OWN.ESTADOS_VALIDACION
(ESTADO_VALIDACION_ID)
LOGGING
TABLESPACE PLGO_IDX
NOPARALLEL;


CREATE UNIQUE INDEX PLGO_OWN.LEGISLATURA_PK ON PLGO_OWN.LEGISLATURA
(LEGISLATURA_ID)
LOGGING
TABLESPACE PLGO_IDX
NOPARALLEL;


CREATE UNIQUE INDEX PLGO_OWN.TIPO_CAMBIO_CONTENIDO_PK ON PLGO_OWN.TIPO_CAMBIO_CONTENIDO
(TIPO_CAMBIO_ID)
LOGGING
TABLESPACE PLGO_IDX
NOPARALLEL;


CREATE UNIQUE INDEX PLGO_OWN.APP_ARCHIVOS_GENERALES_PK ON PLGO_OWN.APP_ARCHIVOS_GENERALES
(ID)
LOGGING
TABLESPACE PLGO_DAT
NOPARALLEL;


CREATE OR REPLACE TRIGGER PLGO_OWN.LEGISLATURA_SEQ_TR
 BEFORE INSERT ON PLGO_OWN.LEGISLATURA FOR EACH ROW
WHEN (
NEW.LEGISLATURA_ID IS NULL
      )
BEGIN
 SELECT LEGISLATURA_SEQ.NEXTVAL INTO :NEW.LEGISLATURA_ID FROM DUAL;
END;
/


CREATE TABLE PLGO_OWN."AspNetUserClaims"
(
  "Id"          NUMBER(10),
  "UserId"      NVARCHAR2(128),
  "ClaimType"   NVARCHAR2(256),
  "ClaimValue"  NVARCHAR2(256)
)
TABLESPACE PLGO_DAT
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PLGO_OWN."AspNetUserLogins"
(
  "LoginProvider"  NVARCHAR2(128),
  "ProviderKey"    NVARCHAR2(128),
  "UserId"         NVARCHAR2(128)
)
TABLESPACE PLGO_DAT
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PLGO_OWN."AspNetUserRoles"
(
  "UserId"  NVARCHAR2(128),
  "RoleId"  NVARCHAR2(128)
)
TABLESPACE PLGO_DAT
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PLGO_OWN.DEPARTAMENTO
(
  DEPARTAMENTO_ID              NUMBER(10)       NOT NULL,
  DESCRIPCION                  VARCHAR2(250 BYTE) NOT NULL,
  LEGISLATURA_ID               NUMBER(10)       NOT NULL,
  VISIBLE                      NUMBER(1)        DEFAULT 1                     NOT NULL,
  ORDEN                        NUMBER(3),
  PORCENTAJE_AVANCE_CALCULADO  NUMBER(5,2)
)
TABLESPACE PLGO_DAT
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PLGO_OWN.USUARIOS
(
  USUARIOID       NVARCHAR2(128)                NOT NULL,
  NOMBRE          VARCHAR2(75 BYTE)             NOT NULL,
  APELLIDOS       VARCHAR2(150 BYTE)            NOT NULL,
  DEPARTAMENTOID  NUMBER(10),
  ULTIMO_ACCESO   DATE,
  FECHA_ALTA      DATE                          NOT NULL
)
TABLESPACE PLGO_DAT
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PLGO_OWN.USUARIOS_PK ON PLGO_OWN.USUARIOS
(USUARIOID)
LOGGING
TABLESPACE PLGO_IDX
NOPARALLEL;


CREATE INDEX PLGO_OWN."IX_AspNetUserClaims_UserId" ON PLGO_OWN."AspNetUserClaims"
("UserId")
LOGGING
TABLESPACE PLGO_IDX
NOPARALLEL;


--  There is no statement for index PLGO_OWN.SYS_C008206.
--  The object is created when the parent object is created.

CREATE INDEX PLGO_OWN."IX_AspNetUserLogins_UserId" ON PLGO_OWN."AspNetUserLogins"
("UserId")
LOGGING
TABLESPACE PLGO_IDX
NOPARALLEL;


--  There is no statement for index PLGO_OWN.SYS_C008207.
--  The object is created when the parent object is created.

CREATE INDEX PLGO_OWN."IX_AspNetUserRoles_RoleId" ON PLGO_OWN."AspNetUserRoles"
("RoleId")
LOGGING
TABLESPACE PLGO_IDX
NOPARALLEL;


CREATE INDEX PLGO_OWN."IX_AspNetUserRoles_UserId" ON PLGO_OWN."AspNetUserRoles"
("UserId")
LOGGING
TABLESPACE PLGO_IDX
NOPARALLEL;


--  There is no statement for index PLGO_OWN.SYS_C008208.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX PLGO_OWN.DEPARTAMENTO_PK ON PLGO_OWN.DEPARTAMENTO
(DEPARTAMENTO_ID)
LOGGING
TABLESPACE PLGO_IDX
NOPARALLEL;


CREATE OR REPLACE TRIGGER PLGO_OWN."AspNetUserClaims_INS_TRG"
  BEFORE INSERT ON PLGO_OWN."AspNetUserClaims"
  FOR EACH ROW
BEGIN
  SELECT PLGO_OWN."AspNetUserClaims_SEQ".NEXTVAL INTO :NEW."Id" FROM DUAL;
END;
/


CREATE OR REPLACE TRIGGER PLGO_OWN.DEPARTAMENTO_SEQ_TR
 BEFORE INSERT ON PLGO_OWN.DEPARTAMENTO FOR EACH ROW
WHEN (
NEW.DEPARTAMENTO_ID IS NULL
      )
BEGIN
 SELECT DEPARTAMENTO_SEQ.NEXTVAL INTO :NEW.DEPARTAMENTO_ID FROM DUAL;
END;
/


CREATE TABLE PLGO_OWN.CONTENIDO
(
  CONTENIDO_ID                   NUMBER(10)     NOT NULL,
  AUTOR_CREACION_USUARIO_ID      NVARCHAR2(128) NOT NULL,
  FECHA_CREACION                 DATE           NOT NULL,
  AUTOR_MODIFICACION_USUARIO_ID  NVARCHAR2(128),
  FECHA_MODIFICACION             DATE,
  VALIDADOR_USUARIO_ID           NVARCHAR2(128),
  ESTADO_VALIDACION_ID           NUMBER(10)     NOT NULL,
  TIPO_CAMBIO_CONTENIDO_ID       NUMBER(10),
  DEPARTAMENTO_ID                NUMBER(10)     NOT NULL,
  VISIBLE                        NUMBER(1)      DEFAULT 1                     NOT NULL,
  COMENTARIO_VALIDADOR           VARCHAR2(2000 BYTE)
)
TABLESPACE PLGO_DAT
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PLGO_OWN.OBJETIVO
(
  CONTENIDO_ID                   NUMBER(10),
  OBJETIVO_ESTRATEGICO           VARCHAR2(2000 BYTE),
  OBJETIVO_ESTRATEGICO_PDTE_VAL  VARCHAR2(2000 BYTE),
  PORCENTAJE_AVANCE_CALCULADO    NUMBER(5,2)
)
TABLESPACE PLGO_DAT
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PLGO_OWN.CONTENIDO_PK ON PLGO_OWN.CONTENIDO
(CONTENIDO_ID)
LOGGING
TABLESPACE PLGO_IDX
NOPARALLEL;


CREATE UNIQUE INDEX PLGO_OWN.OBJETIVO_PK ON PLGO_OWN.OBJETIVO
(CONTENIDO_ID)
LOGGING
TABLESPACE PLGO_IDX
NOPARALLEL;


CREATE OR REPLACE TRIGGER PLGO_OWN.CONTENIDO_SEQ_TR
 BEFORE INSERT ON PLGO_OWN.CONTENIDO FOR EACH ROW
WHEN (
NEW.CONTENIDO_ID IS NULL
      )
BEGIN
 SELECT CONTENIDO_SEQ.NEXTVAL INTO :NEW.CONTENIDO_ID FROM DUAL;
END;
/


CREATE TABLE PLGO_OWN.ACCION
(
  CONTENIDO_ID                    NUMBER(10)    NOT NULL,
  RECURSOS_HUMANOS                VARCHAR2(2000 BYTE),
  RECURSOS_HUMANOS_PDTE_VAL       VARCHAR2(2000 BYTE),
  COSTE_ECONOMICO                 VARCHAR2(2000 BYTE),
  COSTE_ECONOMICO_PDTE_VAL        VARCHAR2(2000 BYTE),
  INSTRUMENTOS_ACT                VARCHAR2(2000 BYTE),
  INSTRUMENTOS_ACT_PDTE_VAL       VARCHAR2(2000 BYTE),
  MEDIOS_OTROS                    VARCHAR2(2000 BYTE),
  MEDIOS_OTROS_PDTE_VAL           VARCHAR2(2000 BYTE),
  TEMPORALIDAD                    VARCHAR2(2000 BYTE),
  TEMPORALIDAD_PDTE_VAL           VARCHAR2(2000 BYTE),
  INDICADOR_SEGUIMIENTO           VARCHAR2(2000 BYTE),
  INDICADOR_SEGUIMIENTO_PDTE_VAL  VARCHAR2(2000 BYTE),
  OBJETIVO_CONTENIDO_ID           NUMBER(10)    NOT NULL,
  ESTADO_SEGUIMIENTO_ID           NUMBER(10),
  ESTADO_SEGUIMIENTO_ID_PDTE_VAL  NUMBER(10),
  ORGANO_RESPONSABLE              VARCHAR2(500 BYTE),
  ORGANO_RESPONSABLE_PDTE_VAL     VARCHAR2(500 BYTE),
  SEGUIMIENTO                     CLOB,
  SEGUIMIENTO_PDTE_VAL            CLOB,
  OBSERVACIONES                   VARCHAR2(2000 BYTE),
  PORCENTAJE_AVANCE               NUMBER(3),
  PORCENTAJE_AVANCE_PDTE_VAL      NUMBER(3)
)
LOB (SEGUIMIENTO_PDTE_VAL) STORE AS (
  TABLESPACE  PLGO_DAT
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
LOB (SEGUIMIENTO) STORE AS (
  TABLESPACE  PLGO_DAT
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
TABLESPACE PLGO_DAT
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PLGO_OWN.ACCION_PK ON PLGO_OWN.ACCION
(CONTENIDO_ID)
LOGGING
TABLESPACE PLGO_IDX
NOPARALLEL;


ALTER TABLE PLGO_OWN.APP_ARCHIVOS_GENERALES ADD (
  CONSTRAINT APP_ARCHIVOS_GENERALES_PK
  PRIMARY KEY
  (ID)
  USING INDEX PLGO_OWN.APP_ARCHIVOS_GENERALES_PK
  ENABLE VALIDATE);

ALTER TABLE PLGO_OWN."AspNetRoles" ADD (
  PRIMARY KEY
  ("Id")
  USING INDEX
    TABLESPACE PLGO_IDX
  ENABLE VALIDATE);

ALTER TABLE PLGO_OWN."AspNetUsers" ADD (
  PRIMARY KEY
  ("Id")
  USING INDEX
    TABLESPACE PLGO_IDX
  ENABLE VALIDATE);

ALTER TABLE PLGO_OWN.ESTADOS_SEGUIMIENTO ADD (
  CONSTRAINT ESTADOS_OBJETIVOS_PK
  PRIMARY KEY
  (ESTADO_SEGUIMIENTO_ID)
  USING INDEX PLGO_OWN.ESTADOS_OBJETIVOS_PK
  ENABLE VALIDATE);

ALTER TABLE PLGO_OWN.ESTADOS_VALIDACION ADD (
  CONSTRAINT ESTADOS_VALIDACION_PK
  PRIMARY KEY
  (ESTADO_VALIDACION_ID)
  USING INDEX PLGO_OWN.ESTADOS_VALIDACION_PK
  ENABLE VALIDATE);

ALTER TABLE PLGO_OWN.LEGISLATURA ADD (
  CONSTRAINT LEGISLATURA_PK
  PRIMARY KEY
  (LEGISLATURA_ID)
  USING INDEX PLGO_OWN.LEGISLATURA_PK
  ENABLE VALIDATE);

ALTER TABLE PLGO_OWN.TIPO_CAMBIO_CONTENIDO ADD (
  CONSTRAINT TIPO_CAMBIO_CONTENIDO_PK
  PRIMARY KEY
  (TIPO_CAMBIO_ID)
  USING INDEX PLGO_OWN.TIPO_CAMBIO_CONTENIDO_PK
  ENABLE VALIDATE);

ALTER TABLE PLGO_OWN."AspNetUserClaims" ADD (
  PRIMARY KEY
  ("Id")
  USING INDEX
    TABLESPACE PLGO_IDX
  ENABLE VALIDATE);

ALTER TABLE PLGO_OWN."AspNetUserLogins" ADD (
  PRIMARY KEY
  ("LoginProvider", "ProviderKey", "UserId")
  USING INDEX
    TABLESPACE PLGO_IDX
  ENABLE VALIDATE);

ALTER TABLE PLGO_OWN."AspNetUserRoles" ADD (
  PRIMARY KEY
  ("UserId", "RoleId")
  USING INDEX
    TABLESPACE PLGO_IDX
  ENABLE VALIDATE);

ALTER TABLE PLGO_OWN.DEPARTAMENTO ADD (
  CONSTRAINT DEPARTAMENTO_PK
  PRIMARY KEY
  (DEPARTAMENTO_ID)
  USING INDEX PLGO_OWN.DEPARTAMENTO_PK
  ENABLE VALIDATE);

ALTER TABLE PLGO_OWN.USUARIOS ADD (
  CONSTRAINT USUARIOS_PK
  PRIMARY KEY
  (USUARIOID)
  USING INDEX PLGO_OWN.USUARIOS_PK
  ENABLE VALIDATE);

ALTER TABLE PLGO_OWN.CONTENIDO ADD (
  CONSTRAINT CONTENIDO_PK
  PRIMARY KEY
  (CONTENIDO_ID)
  USING INDEX PLGO_OWN.CONTENIDO_PK
  ENABLE VALIDATE);

ALTER TABLE PLGO_OWN.OBJETIVO ADD (
  CONSTRAINT OBJETIVO_PK
  PRIMARY KEY
  (CONTENIDO_ID)
  USING INDEX PLGO_OWN.OBJETIVO_PK
  ENABLE VALIDATE);

ALTER TABLE PLGO_OWN.ACCION ADD (
  CONSTRAINT ACCION_PK
  PRIMARY KEY
  (CONTENIDO_ID)
  USING INDEX PLGO_OWN.ACCION_PK
  ENABLE VALIDATE);

ALTER TABLE PLGO_OWN."AspNetUserClaims" ADD (
  CONSTRAINT "FK_UserClaims_Users" 
  FOREIGN KEY ("UserId") 
  REFERENCES PLGO_OWN."AspNetUsers" ("Id")
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE PLGO_OWN."AspNetUserLogins" ADD (
  CONSTRAINT "FK_UserLogins_Users" 
  FOREIGN KEY ("UserId") 
  REFERENCES PLGO_OWN."AspNetUsers" ("Id")
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE PLGO_OWN."AspNetUserRoles" ADD (
  CONSTRAINT "FK_UserRoles_Roles" 
  FOREIGN KEY ("RoleId") 
  REFERENCES PLGO_OWN."AspNetRoles" ("Id")
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT "FK_UserRoles_Users" 
  FOREIGN KEY ("UserId") 
  REFERENCES PLGO_OWN."AspNetUsers" ("Id")
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE PLGO_OWN.DEPARTAMENTO ADD (
  FOREIGN KEY (LEGISLATURA_ID) 
  REFERENCES PLGO_OWN.LEGISLATURA (LEGISLATURA_ID)
  ENABLE VALIDATE);

ALTER TABLE PLGO_OWN.USUARIOS ADD (
  FOREIGN KEY (USUARIOID) 
  REFERENCES PLGO_OWN."AspNetUsers" ("Id")
  ENABLE VALIDATE,
  FOREIGN KEY (DEPARTAMENTOID) 
  REFERENCES PLGO_OWN.DEPARTAMENTO (DEPARTAMENTO_ID)
  ENABLE VALIDATE);

ALTER TABLE PLGO_OWN.CONTENIDO ADD (
  CONSTRAINT CONTENIDO_R01 
  FOREIGN KEY (AUTOR_CREACION_USUARIO_ID) 
  REFERENCES PLGO_OWN.USUARIOS (USUARIOID)
  ENABLE VALIDATE,
  CONSTRAINT CONTENIDO_R02 
  FOREIGN KEY (AUTOR_MODIFICACION_USUARIO_ID) 
  REFERENCES PLGO_OWN.USUARIOS (USUARIOID)
  ENABLE VALIDATE,
  CONSTRAINT CONTENIDO_R03 
  FOREIGN KEY (VALIDADOR_USUARIO_ID) 
  REFERENCES PLGO_OWN.USUARIOS (USUARIOID)
  ENABLE VALIDATE,
  CONSTRAINT CONTENIDO_R04 
  FOREIGN KEY (ESTADO_VALIDACION_ID) 
  REFERENCES PLGO_OWN.ESTADOS_VALIDACION (ESTADO_VALIDACION_ID)
  ENABLE VALIDATE,
  CONSTRAINT CONTENIDO_R05 
  FOREIGN KEY (TIPO_CAMBIO_CONTENIDO_ID) 
  REFERENCES PLGO_OWN.TIPO_CAMBIO_CONTENIDO (TIPO_CAMBIO_ID)
  ENABLE VALIDATE,
  CONSTRAINT CONTENIDO_R06 
  FOREIGN KEY (DEPARTAMENTO_ID) 
  REFERENCES PLGO_OWN.DEPARTAMENTO (DEPARTAMENTO_ID)
  ENABLE VALIDATE);

ALTER TABLE PLGO_OWN.OBJETIVO ADD (
  FOREIGN KEY (CONTENIDO_ID) 
  REFERENCES PLGO_OWN.CONTENIDO (CONTENIDO_ID)
  ENABLE VALIDATE);

ALTER TABLE PLGO_OWN.ACCION ADD (
  FOREIGN KEY (ESTADO_SEGUIMIENTO_ID) 
  REFERENCES PLGO_OWN.ESTADOS_SEGUIMIENTO (ESTADO_SEGUIMIENTO_ID)
  ENABLE VALIDATE,
  FOREIGN KEY (ESTADO_SEGUIMIENTO_ID_PDTE_VAL) 
  REFERENCES PLGO_OWN.ESTADOS_SEGUIMIENTO (ESTADO_SEGUIMIENTO_ID)
  ENABLE VALIDATE,
  FOREIGN KEY (CONTENIDO_ID) 
  REFERENCES PLGO_OWN.CONTENIDO (CONTENIDO_ID)
  ENABLE VALIDATE,
  FOREIGN KEY (OBJETIVO_CONTENIDO_ID) 
  REFERENCES PLGO_OWN.OBJETIVO (CONTENIDO_ID)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON PLGO_OWN.APP_ARCHIVOS_GENERALES TO PLGO_USR;

GRANT DELETE, INSERT, SELECT, UPDATE ON PLGO_OWN."AspNetRoles" TO PLGO_USR;

GRANT DELETE, INSERT, SELECT, UPDATE ON PLGO_OWN."AspNetUsers" TO PLGO_USR;

GRANT DELETE, INSERT, SELECT, UPDATE ON PLGO_OWN.ESTADOS_SEGUIMIENTO TO PLGO_USR;

GRANT DELETE, INSERT, SELECT, UPDATE ON PLGO_OWN.ESTADOS_VALIDACION TO PLGO_USR;

GRANT DELETE, INSERT, SELECT, UPDATE ON PLGO_OWN.LEGISLATURA TO PLGO_USR;

GRANT DELETE, INSERT, SELECT, UPDATE ON PLGO_OWN.TIPO_CAMBIO_CONTENIDO TO PLGO_USR;

GRANT DELETE, INSERT, SELECT, UPDATE ON PLGO_OWN."AspNetUserClaims" TO PLGO_USR;

GRANT DELETE, INSERT, SELECT, UPDATE ON PLGO_OWN."AspNetUserLogins" TO PLGO_USR;

GRANT DELETE, INSERT, SELECT, UPDATE ON PLGO_OWN."AspNetUserRoles" TO PLGO_USR;

GRANT DELETE, INSERT, SELECT, UPDATE ON PLGO_OWN.DEPARTAMENTO TO PLGO_USR;

GRANT DELETE, INSERT, SELECT, UPDATE ON PLGO_OWN.USUARIOS TO PLGO_USR;

GRANT DELETE, INSERT, SELECT, UPDATE ON PLGO_OWN.CONTENIDO TO PLGO_USR;

GRANT DELETE, INSERT, SELECT, UPDATE ON PLGO_OWN.OBJETIVO TO PLGO_USR;

GRANT DELETE, INSERT, SELECT, UPDATE ON PLGO_OWN.ACCION TO PLGO_USR;
